# Generated by Django 2.1 on 2019-02-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OauthUser',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('discriminator', models.CharField(max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_token', models.CharField(max_length=48)),
                ('refresh_token', models.CharField(max_length=48)),
            ],
        ),
    ]
