# Generated by Django 2.1 on 2019-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='view',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
