# Generated by Django 2.1 on 2019-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_front',
            field=models.BooleanField(default=False),
        ),
    ]
