# Generated by Django 2.1 on 2019-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_display_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
