# Generated by Django 2.1 on 2019-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
