# Generated by Django 2.1 on 2019-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
